### ISSUE TITLE
如何签名tron交易？

### ISSUE THREAD

**Issue by dinghung** [0xcregis/anychain#195]
<img width="866" alt="image" src="https://github.com/0xcregis/anychain/assets/6938390/2762c8cf-4505-4a7b-bd8d-9fe74559314a">

有点看不懂怎么用的，是否有更详细的demo或者文档

官方是否有组件交流群的想法，相对web3j网上资料多，查找使用资料翻遍，anychain在使用上成本有点高，如果有交流群会方便很多，能吸引更多人去用，降低他们使用成本

**Comment by Shawndslee** [comment]
你好，加入 https://t.me/anychain_sdk Telegram交流群，我们有Demo
