### ISSUE TITLE
anychian结构交流

### ISSUE THREAD

**Issue by hellogaod** [0xcregis/anychain#283]
首先对提供anychian的贡献者表示感谢，给我学习的机会。其次从交流角度来讲，我提几个自己的观点，从结构角度来讲，这样的结构目前没问题（当然我个人可能有洁癖看着不舒服），但是随着项目的扩大需要提前规划。下面我提一下自己的观点：
1.btc、eth、tron等具体实现可以提炼到impl模块：anychain-impl
2.anychain-core其实是anychain-api，提供接口的地方，整个anychain都是core；
3.anychain-kms这里提供的是bip32和bip39标准，是否可以再起一个anychain-standard模块，用于存放kms以及后期其他标准；
4.还可以预留一个模块prerelease模块，包括两个功能：1.预留api：需要开发的api；2.收集一些可以开发的功能说明；

**Comment by loki-cmu** [comment]
Thank you for your feedback. 
1. We've moved BTC, ETH, and Tron crates to the crates directory.
2. We're keeping anychain-kms as is for compatibility reasons, but you're welcome to fork an anychain-standard version.

**Comment by hellogaod** [comment]
good~
